### ISSUE TITLE
Не работает $function с параметрами после build

### ISSUE THREAD

**Issue by alexeyten** [razetdinov/dollar-config#1]
После build-а функция уже с параметрами и получается вложенный массив.
`{ '$function': [ [ 'test', { data: 42 } ], { ENV: 'test' } ] }`. Надо склеивать параметры функции или обрабатывать вложенный массив.

```js
'use strict';

const buildConfig = require('dollar-config/build');
const DollarConfig = require('dollar-config');

const source = {
    func: { $function: [ 'test', { data: 42 } ] }
};

const functions = {
    test: (params) => params.data
};

const good = new DollarConfig(source, { functions });
console.log('GOOD', good.get('func', {})); // => GOOD 42

const builded = buildConfig(source, { ENV: 'test' });
const bad = new DollarConfig(builded, { functions });

console.log('BAD', bad.get('func', {})); // Кидает ошибку
/*
.../node_modules/dollar-config/index.js:189
    path = path.split('.');
                ^
    TypeError: path.split is not a function
    at get (.../node_modules/dollar-config/index.js:189:17)
    at Object.$function (.../node_modules/dollar-config/index.js:44:16)
    at Config._resolve (.../node_modules/dollar-config/index.js:110:44)
    at Config.get (.../node_modules/dollar-config/index.js:80:30)
    at ...
*/
```

**Comment by razetdinov** [comment]
Возможность передавать параметры в функцию пока не открыта (и валидацию через ajv не пройдёт). Я думал над этим и задал себе такой вопрос: можно при вызове переопределять (доопределять) `params`?

**Comment by alexeyten** [comment]
Я хотел сделать примерно такую функцию `getResHeader` и использовать в логировании
```js
getResHeader(req, name) {
    return req.res.getHeader(name) || '';
}
```

```yaml
redirect_to: { $function: [ getResHeader, 'Location' ] }
```

**Comment by razetdinov** [comment]
То есть первый «аргумент» в вызове превращается во второй в декларации. Если так норм, можно сделать.

**Comment by alexeyten** [comment]
Мне ещё не нравится, что при вызове функции происходит склеивание параметров из build и текущего req. https://github.com/razetdinov/dollar-config/blob/master/index.js#L43

**Comment by razetdinov** [comment]
Это сделано на случай, если параметр, который мы инлайним, используется внутри функции. Заранее мы это знать не можем, поэтому мёржим параметры. Функция должна вести себя одинаково как со сборкой, так и без. Пока склоняюсь к такому решению. Первым элементом название функции, вторым — массив аргументов, третьим — собранные параметры (если есть).

До сборки:
```js
redirect_to: { $function: [ getResHeader, [ 'Location' ] ] }
```

После сборки:
```js
redirect_to: { $function: [ getResHeader, [ 'Location' ], { ENVIRONMENT: 'production' } ] }
```

**Comment by alexeyten** [comment]
Тоже какая-то лажа. Надо ещё подумать

**Comment by alexeyten** [comment]
А обязательно массив?
Может как-то так?
```yaml
$function:
  name: getResHeader
  args: [ Location ]
  bind: { ENVIRONMENT: production }
```
